parameters:
#    bk_meteo.example.class: Bk\MeteoBundle\Example
    OpenWeatherMap:
        country:
            france: [3020686,2998324,2988507]
        city:
            dunkerque: 3020686
            lille: 2998324
            paris: 2988507

services:
#    bk_meteo.example:
#        class: %bk_meteo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
