<?php

namespace Bk\MeteoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MaitreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeatherRepository extends EntityRepository
{
}
